// Shared by server and client. Zero deps so it can be imported anywhere.
// Server functions must NOT throw AppError classes across the RPC boundary —
// serialize the code into a plain Error message: `throw new Error("APP-XXX-###: <detalle>")`.
// The client mapper (`src/lib/errors/map.ts`) extracts the code by regex.

export const APP_ERROR_REGEX = /APP-[A-Z]+-\d{3}/;

// Canonical codes shared by server + client.
export const ERR = {
  // AUTH
  LOGIN_INVALID: "APP-AUTH-001",
  SESSION_EXPIRED: "APP-AUTH-002",
  EMAIL_TAKEN: "APP-AUTH-003",
  TOO_MANY_ATTEMPTS: "APP-AUTH-004",
  PASSWORD_WEAK: "APP-AUTH-006",
  PASSWORD_MISMATCH: "APP-AUTH-007",
  EMAIL_NOT_CONFIRMED: "APP-AUTH-008",
  RECOVERY_LINK_EXPIRED: "APP-AUTH-009",

  // PERMISSIONS / PAYWALL
  PREMIUM_REQUIRED: "APP-PERM-001",
  FORBIDDEN: "APP-PERM-002",
  NO_UNLOCKS_AVAILABLE: "APP-PAY-002",


  // AI GATEWAY
  AI_RATE_LIMITED: "APP-AI-001",
  AI_UNAVAILABLE: "APP-AI-002",
  AI_BAD_RESPONSE: "APP-AI-003",
  AI_BAD_RECIPE: "APP-AI-004",
  AI_BLOCKED: "APP-AI-005",

  // VOICE (Kiko por voz)
  VOICE_LIMIT_REACHED: "APP-VOICE-001",
  VOICE_MIC_DENIED: "APP-VOICE-002",
  VOICE_UNAVAILABLE: "APP-VOICE-003",


  // FILES
  FILE_BAD_FORMAT: "APP-FILE-001",
  FILE_TOO_LARGE: "APP-FILE-002",
  FILE_READ_FAILED: "APP-FILE-003",

  // FORM DATA
  FORM_INVALID: "APP-DATA-001",

  // RECIPES
  RECIPE_NOT_FOUND: "APP-RCP-001",
  RECIPE_ALREADY_MINE: "APP-RCP-002",
  RECIPE_NOT_SHAREABLE: "APP-RCP-003",
  RECIPE_SAVE_FAILED: "APP-RCP-004",

  // DISCOVER CHATS
  CHAT_NOT_FOUND: "APP-CHAT-001",
  CHAT_CREATE_FAILED: "APP-CHAT-002",
  CHAT_DELETE_FAILED: "APP-CHAT-003",
  CHAT_TOO_LARGE: "APP-CHAT-004",

  // NETWORK
  NETWORK_OFFLINE: "APP-NET-001",
  NETWORK_TIMEOUT: "APP-NET-002",
  SERVER_ERROR: "APP-NET-003",

  // CAMERA / QR
  CAMERA_DENIED: "APP-CAM-001",
  CAMERA_NOT_FOUND: "APP-CAM-002",
  QR_INVALID: "APP-QR-001",

  // SHARING
  SHARE_COPY_FAILED: "APP-SHARE-001",

  // CSV
  CSV_BAD_HEADER: "APP-CSV-001",
  CSV_BAD_ROWS: "APP-CSV-002",

  // IMAGES
  IMAGE_PROCESS_FAILED: "APP-IMG-001",
  IMAGE_PREPARE_FAILED: "APP-IMG-002",

  // LOCAL STORAGE
  STORAGE_WRITE_FAILED: "APP-STORE-001",

  // UPLOADS
  UPLOAD_FAILED: "APP-UPLOAD-001",

  // URL IMPORT
  URL_FETCH_FAILED: "APP-URL-001",

  // GUEST MIGRATION
  GUEST_MIGRATION_FAILED: "APP-GUEST-001",

  // PROFILE
  PROFILE_UPDATE_FAILED: "APP-PROFILE-001",

  // ADMIN
  ADMIN_OP_FAILED: "APP-ADMIN-001",

  // SYSTEM
  UNKNOWN: "APP-SYS-001",
} as const;

export type AppErrorCode = (typeof ERR)[keyof typeof ERR];
