/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthAdminRouteImport } from './routes/auth-admin'
import { Route as ChefRouteImport } from './routes/chef'
import { Route as DescubrirRouteImport } from './routes/descubrir'
import { Route as MelikBakeryRouteImport } from './routes/melik-bakery'
import { Route as MelikPlusRouteImport } from './routes/melik-plus'
import { Route as NotificacionesRouteImport } from './routes/notificaciones'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedDraftsRouteImport } from './routes/_authenticated/drafts'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCatalogoRouteImport } from './routes/admin.catalogo'
import { Route as AdminNotificacionesRouteImport } from './routes/admin.notificaciones'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth.update-password'
import { Route as DescubrirIndexRouteImport } from './routes/descubrir.index'
import { Route as DescubrirChatIdRouteImport } from './routes/descubrir.$chatId'
import { Route as AuthenticatedSharedShareTokenRouteImport } from './routes/_authenticated/shared.$shareToken'
import { Route as ApiPublicHooksMelikPlusRenewRouteImport } from './routes/api/public/hooks/melik-plus-renew'
import { Route as ApiPublicHooksTrialExpiringReminderRouteImport } from './routes/api/public/hooks/trial-expiring-reminder'
import { Route as ApiPublicFilesBucketSplatRouteImport } from './routes/api/public/files/$bucket/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/auth-admin',
  path: '/auth-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefRoute = ChefRouteImport.update({
  id: '/chef',
  path: '/chef',
  getParentRoute: () => rootRouteImport,
} as any)
const DescubrirRoute = DescubrirRouteImport.update({
  id: '/descubrir',
  path: '/descubrir',
  getParentRoute: () => rootRouteImport,
} as any)
const MelikBakeryRoute = MelikBakeryRouteImport.update({
  id: '/melik-bakery',
  path: '/melik-bakery',
  getParentRoute: () => rootRouteImport,
} as any)
const MelikPlusRoute = MelikPlusRouteImport.update({
  id: '/melik-plus',
  path: '/melik-plus',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacionesRoute = NotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDraftsRoute = AuthenticatedDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogoRoute = AdminCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificacionesRoute = AdminNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => AuthRoute,
} as any)
const DescubrirIndexRoute = DescubrirIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DescubrirRoute,
} as any)
const DescubrirChatIdRoute = DescubrirChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => DescubrirRoute,
} as any)
const AuthenticatedSharedShareTokenRoute =
  AuthenticatedSharedShareTokenRouteImport.update({
    id: '/shared/$shareToken',
    path: '/shared/$shareToken',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksMelikPlusRenewRoute =
  ApiPublicHooksMelikPlusRenewRouteImport.update({
    id: '/api/public/hooks/melik-plus-renew',
    path: '/api/public/hooks/melik-plus-renew',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTrialExpiringReminderRoute =
  ApiPublicHooksTrialExpiringReminderRouteImport.update({
    id: '/api/public/hooks/trial-expiring-reminder',
    path: '/api/public/hooks/trial-expiring-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFilesBucketSplatRoute =
  ApiPublicFilesBucketSplatRouteImport.update({
    id: '/api/public/files/$bucket/$',
    path: '/api/public/files/$bucket/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth-admin': typeof AuthAdminRoute
  '/chef': typeof ChefRoute
  '/descubrir': typeof DescubrirRouteWithChildren
  '/melik-bakery': typeof MelikBakeryRoute
  '/melik-plus': typeof MelikPlusRoute
  '/notificaciones': typeof NotificacionesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/catalogo': typeof AdminCatalogoRoute
  '/admin/notificaciones': typeof AdminNotificacionesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/descubrir/$chatId': typeof DescubrirChatIdRoute
  '/admin/': typeof AdminIndexRoute
  '/descubrir/': typeof DescubrirIndexRoute
  '/shared/$shareToken': typeof AuthenticatedSharedShareTokenRoute
  '/api/public/hooks/melik-plus-renew': typeof ApiPublicHooksMelikPlusRenewRoute
  '/api/public/hooks/trial-expiring-reminder': typeof ApiPublicHooksTrialExpiringReminderRoute
  '/api/public/files/$bucket/$': typeof ApiPublicFilesBucketSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth-admin': typeof AuthAdminRoute
  '/chef': typeof ChefRoute
  '/melik-bakery': typeof MelikBakeryRoute
  '/melik-plus': typeof MelikPlusRoute
  '/notificaciones': typeof NotificacionesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/catalogo': typeof AdminCatalogoRoute
  '/admin/notificaciones': typeof AdminNotificacionesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/descubrir/$chatId': typeof DescubrirChatIdRoute
  '/admin': typeof AdminIndexRoute
  '/descubrir': typeof DescubrirIndexRoute
  '/shared/$shareToken': typeof AuthenticatedSharedShareTokenRoute
  '/api/public/hooks/melik-plus-renew': typeof ApiPublicHooksMelikPlusRenewRoute
  '/api/public/hooks/trial-expiring-reminder': typeof ApiPublicHooksTrialExpiringReminderRoute
  '/api/public/files/$bucket/$': typeof ApiPublicFilesBucketSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth-admin': typeof AuthAdminRoute
  '/chef': typeof ChefRoute
  '/descubrir': typeof DescubrirRouteWithChildren
  '/melik-bakery': typeof MelikBakeryRoute
  '/melik-plus': typeof MelikPlusRoute
  '/notificaciones': typeof NotificacionesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/drafts': typeof AuthenticatedDraftsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/admin/catalogo': typeof AdminCatalogoRoute
  '/admin/notificaciones': typeof AdminNotificacionesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/descubrir/$chatId': typeof DescubrirChatIdRoute
  '/admin/': typeof AdminIndexRoute
  '/descubrir/': typeof DescubrirIndexRoute
  '/_authenticated/shared/$shareToken': typeof AuthenticatedSharedShareTokenRoute
  '/api/public/hooks/melik-plus-renew': typeof ApiPublicHooksMelikPlusRenewRoute
  '/api/public/hooks/trial-expiring-reminder': typeof ApiPublicHooksTrialExpiringReminderRoute
  '/api/public/files/$bucket/$': typeof ApiPublicFilesBucketSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/auth-admin'
    | '/chef'
    | '/descubrir'
    | '/melik-bakery'
    | '/melik-plus'
    | '/notificaciones'
    | '/sitemap.xml'
    | '/drafts'
    | '/profile'
    | '/admin/catalogo'
    | '/admin/notificaciones'
    | '/admin/usuarios'
    | '/auth/reset'
    | '/auth/update-password'
    | '/descubrir/$chatId'
    | '/admin/'
    | '/descubrir/'
    | '/shared/$shareToken'
    | '/api/public/hooks/melik-plus-renew'
    | '/api/public/hooks/trial-expiring-reminder'
    | '/api/public/files/$bucket/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth-admin'
    | '/chef'
    | '/melik-bakery'
    | '/melik-plus'
    | '/notificaciones'
    | '/sitemap.xml'
    | '/drafts'
    | '/profile'
    | '/admin/catalogo'
    | '/admin/notificaciones'
    | '/admin/usuarios'
    | '/auth/reset'
    | '/auth/update-password'
    | '/descubrir/$chatId'
    | '/admin'
    | '/descubrir'
    | '/shared/$shareToken'
    | '/api/public/hooks/melik-plus-renew'
    | '/api/public/hooks/trial-expiring-reminder'
    | '/api/public/files/$bucket/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/auth-admin'
    | '/chef'
    | '/descubrir'
    | '/melik-bakery'
    | '/melik-plus'
    | '/notificaciones'
    | '/sitemap.xml'
    | '/_authenticated/drafts'
    | '/_authenticated/profile'
    | '/admin/catalogo'
    | '/admin/notificaciones'
    | '/admin/usuarios'
    | '/auth/reset'
    | '/auth/update-password'
    | '/descubrir/$chatId'
    | '/admin/'
    | '/descubrir/'
    | '/_authenticated/shared/$shareToken'
    | '/api/public/hooks/melik-plus-renew'
    | '/api/public/hooks/trial-expiring-reminder'
    | '/api/public/files/$bucket/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AuthAdminRoute: typeof AuthAdminRoute
  ChefRoute: typeof ChefRoute
  DescubrirRoute: typeof DescubrirRouteWithChildren
  MelikBakeryRoute: typeof MelikBakeryRoute
  MelikPlusRoute: typeof MelikPlusRoute
  NotificacionesRoute: typeof NotificacionesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicHooksMelikPlusRenewRoute: typeof ApiPublicHooksMelikPlusRenewRoute
  ApiPublicHooksTrialExpiringReminderRoute: typeof ApiPublicHooksTrialExpiringReminderRoute
  ApiPublicFilesBucketSplatRoute: typeof ApiPublicFilesBucketSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-admin': {
      id: '/auth-admin'
      path: '/auth-admin'
      fullPath: '/auth-admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef': {
      id: '/chef'
      path: '/chef'
      fullPath: '/chef'
      preLoaderRoute: typeof ChefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descubrir': {
      id: '/descubrir'
      path: '/descubrir'
      fullPath: '/descubrir'
      preLoaderRoute: typeof DescubrirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/melik-bakery': {
      id: '/melik-bakery'
      path: '/melik-bakery'
      fullPath: '/melik-bakery'
      preLoaderRoute: typeof MelikBakeryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/melik-plus': {
      id: '/melik-plus'
      path: '/melik-plus'
      fullPath: '/melik-plus'
      preLoaderRoute: typeof MelikPlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificaciones': {
      id: '/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof NotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/drafts': {
      id: '/_authenticated/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof AuthenticatedDraftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogo': {
      id: '/admin/catalogo'
      path: '/catalogo'
      fullPath: '/admin/catalogo'
      preLoaderRoute: typeof AdminCatalogoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notificaciones': {
      id: '/admin/notificaciones'
      path: '/notificaciones'
      fullPath: '/admin/notificaciones'
      preLoaderRoute: typeof AdminNotificacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/descubrir/': {
      id: '/descubrir/'
      path: '/'
      fullPath: '/descubrir/'
      preLoaderRoute: typeof DescubrirIndexRouteImport
      parentRoute: typeof DescubrirRoute
    }
    '/descubrir/$chatId': {
      id: '/descubrir/$chatId'
      path: '/$chatId'
      fullPath: '/descubrir/$chatId'
      preLoaderRoute: typeof DescubrirChatIdRouteImport
      parentRoute: typeof DescubrirRoute
    }
    '/_authenticated/shared/$shareToken': {
      id: '/_authenticated/shared/$shareToken'
      path: '/shared/$shareToken'
      fullPath: '/shared/$shareToken'
      preLoaderRoute: typeof AuthenticatedSharedShareTokenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/melik-plus-renew': {
      id: '/api/public/hooks/melik-plus-renew'
      path: '/api/public/hooks/melik-plus-renew'
      fullPath: '/api/public/hooks/melik-plus-renew'
      preLoaderRoute: typeof ApiPublicHooksMelikPlusRenewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/trial-expiring-reminder': {
      id: '/api/public/hooks/trial-expiring-reminder'
      path: '/api/public/hooks/trial-expiring-reminder'
      fullPath: '/api/public/hooks/trial-expiring-reminder'
      preLoaderRoute: typeof ApiPublicHooksTrialExpiringReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/files/$bucket/$': {
      id: '/api/public/files/$bucket/$'
      path: '/api/public/files/$bucket/$'
      fullPath: '/api/public/files/$bucket/$'
      preLoaderRoute: typeof ApiPublicFilesBucketSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDraftsRoute: typeof AuthenticatedDraftsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSharedShareTokenRoute: typeof AuthenticatedSharedShareTokenRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDraftsRoute: AuthenticatedDraftsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSharedShareTokenRoute: AuthenticatedSharedShareTokenRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminCatalogoRoute: typeof AdminCatalogoRoute
  AdminNotificacionesRoute: typeof AdminNotificacionesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCatalogoRoute: AdminCatalogoRoute,
  AdminNotificacionesRoute: AdminNotificacionesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthResetRoute: typeof AuthResetRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetRoute: AuthResetRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DescubrirRouteChildren {
  DescubrirChatIdRoute: typeof DescubrirChatIdRoute
  DescubrirIndexRoute: typeof DescubrirIndexRoute
}

const DescubrirRouteChildren: DescubrirRouteChildren = {
  DescubrirChatIdRoute: DescubrirChatIdRoute,
  DescubrirIndexRoute: DescubrirIndexRoute,
}

const DescubrirRouteWithChildren = DescubrirRoute._addFileChildren(
  DescubrirRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AuthAdminRoute: AuthAdminRoute,
  ChefRoute: ChefRoute,
  DescubrirRoute: DescubrirRouteWithChildren,
  MelikBakeryRoute: MelikBakeryRoute,
  MelikPlusRoute: MelikPlusRoute,
  NotificacionesRoute: NotificacionesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicHooksMelikPlusRenewRoute: ApiPublicHooksMelikPlusRenewRoute,
  ApiPublicHooksTrialExpiringReminderRoute:
    ApiPublicHooksTrialExpiringReminderRoute,
  ApiPublicFilesBucketSplatRoute: ApiPublicFilesBucketSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
